# @host = localhost:3000
###
POST http://localhost:3000/signup HTTP/1.1
content-type: application/json

{
    "email": "marcelo.figterenciani@gmail.com",
    "lastname": "Terenciani",
    "name": "Marcelo",
    "phone": "44998887342",
    "password": "12345678"
}

###

# E-mail not found
POST http://localhost:3000/signin HTTP/1.1
content-type: application/json

{
    "email": "marcelo.figueiredo@gmail.com",
    "password": "12345"
}

###
# Password wrong

POST http://localhost:3000/signin HTTP/1.1
content-type: application/json

{
    "email": "marcelo.figterenciani@gmail.com",
    "password": "12345678"
}

###
#User valid
POST http://localhost:3000/signin HTTP/1.1
content-type: application/json

{
    "email": "marcelo.terenciani@gmail.com",
    "password": "35d4a64acd0ab92158a8089f2a0d74c5"
}
###

# Recovery PASS
POST http://localhost:3000/recovery HTTP/1.1
content-type: application/json

{
    "email": "marcelo.figterenciani@gmail.com"
}




